package heckers.projecti;



import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aarya
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login2
     */
    public login() {
        initComponents();
        username.setBackground(new java.awt.Color(0,0,0,1));
        pass.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        wrong = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newuser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Log In");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        exit.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 204, 204));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 20, 20));

        wrong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        wrong.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 290, 30));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Forget Password ?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 170, 30));

        newuser.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        newuser.setForeground(new java.awt.Color(255, 153, 51));
        newuser.setText("New User");
        newuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserMouseClicked(evt);
            }
        });
        jPanel1.add(newuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 90, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 230, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 132, 230, 10));

        username.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("UserName");
        username.setBorder(null);
        username.setCaretColor(new java.awt.Color(255, 255, 255));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 230, 32));

        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("password");
        pass.setToolTipText("");
        pass.setBorder(null);
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 230, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\aarya\\Downloads\\InMan-logos_white.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 300, 230));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\InMan\\projectI\\projectI\\lib\\img\\wallpaperflare-cropped (1).jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        if(username.getText().equals("UserName")){
            try {
                Thread.sleep(400);
            } catch (InterruptedException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            username.setText("");

        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        

        if(username.getText().equals("")){
            try {
                Thread.sleep(400);
            } catch (InterruptedException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            username.setText("UserName");

        }
    }//GEN-LAST:event_usernameFocusLost

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE){
            pass.setText("");
        }
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             String user= username.getText();
        String passs= pass.getText();
        //ADMIN LOGIN
        if(user.contains("Admin")&& passs.contains("2022")){
            menuAdmin m1 =new menuAdmin();
            m1.setVisible(true);
            setVisible(false);
        }
        //USER LOGIN
        else if(user.contains("trial")&& passs.contains("2020")){
           Menu m1 =new Menu();
            m1.setVisible(true);
            setVisible(false);   
        }
        else
        {
            wrong.setText("ENTER VALID USERNAME & PASSWORD");
            setVisible(true);
        }
        
        
       
        
        }
    }//GEN-LAST:event_passKeyPressed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        String user= username.getText();
        String passs= pass.getText();
        if(user.contains("Admin")&& passs.contains("2022")){
            menuAdmin m1 =new menuAdmin();
            m1.setVisible(true);
            setVisible(false);
            
            
        }
        else if(user.contains("trial")&& passs.contains("2020")){
           Menu m1 =new Menu();
            m1.setVisible(true);
            setVisible(false);
            
            
        }
         
        else
        {
            wrong.setText("ENTER VALID USERNAME & PASSWORD");
            setVisible(true);
        }
//        String pass = pass.getText();
    }//GEN-LAST:event_loginMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

    }//GEN-LAST:event_loginActionPerformed

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
         
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                String user = username.getText();
                String passs = pass.getText();
                //ADMIN LOGIN
                if (user.contains("Admin") && passs.contains("2022")) {
                    menuAdmin m1 = new menuAdmin();
                    m1.setVisible(true);
                    setVisible(false);
                } //USER LOGIN
                else if (user.contains("trial") && passs.contains("2020")) {
                    Menu m1 = new Menu();
                    m1.setVisible(true);
                    setVisible(false);                    
                } else {
                    wrong.setText("ENTER VALID USERNAME & PASSWORD");
                    setVisible(true);
                }
                
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_loginKeyPressed

    private void newuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserMouseClicked
        signup s= new signup();
        s.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_newuserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton login;
    private javax.swing.JLabel newuser;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField username;
    private javax.swing.JLabel wrong;
    // End of variables declaration//GEN-END:variables
}
