/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package heckers.projecti;

import javax.swing.JOptionPane;

/**
 *
 * @author heckers
 */
public final class spalsh extends javax.swing.JFrame {

    /**
     * Creates new form spalsh
     */
    public spalsh() {
        initComponents();
//       scaleImage();
    }

//    public void scaleImage(){
//        ImageIcon icon = new ImageIcon("\"C:\\Users\\aarya\\Downloads\\logo.png\"");
//        Image img =icon.getImage();
//        Image imgScale = img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon scaledIcon = new ImageIcon(imgScale);
//        jLabel3.setIcon(scaledIcon);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadbar = new javax.swing.JProgressBar();
        loading = new javax.swing.JLabel();
        loadingvalue = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(getPreferredSize());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(loadbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 290, 620, 15));

        loading.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        loading.setForeground(new java.awt.Color(102, 102, 102));
        loading.setText("Loading...");
        jPanel1.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 360, -1));

        loadingvalue.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        loadingvalue.setForeground(new java.awt.Color(102, 102, 102));
        loadingvalue.setText("0%");
        jPanel1.add(loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 40, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\InMan\\projectI\\projectI\\lib\\img\\logo_auto_x2 (1).jpg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 560, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(598, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spalsh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        spalsh sp =new spalsh();
       sp.setVisible(true);
        
            try{
                for (int i=0;i<=100;i++){
                    Thread.sleep(100);
                    sp.loadingvalue.setText(i+"%");

                    if(i==10){
                        sp.loading.setText("Turning on Modules....");
                    }

                    if(i==20){
                        sp.loading.setText("Loading Modules.....");
                    }
                    if(i==50){
                        sp.loading.setText("Connecting to the Database....");
                    }
                    if(i==70){
                        sp.loading.setText("Connection Successfull.....");
                    }
                    if(i==90){
                        sp.loading.setText("Launching Application....");
                    }
                    if(i==100){
                        sp.setVisible(false);
                        login l=new login();
                        l.setVisible(true);
                    }
                sp.loadbar.setValue(i);
            }
        }catch(InterruptedException e){
           JOptionPane.showMessageDialog(null,e);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadbar;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel loadingvalue;
    // End of variables declaration//GEN-END:variables
}
